module.exports = {
  projects: [
    '<rootDir>/apps/client',
    '<rootDir>/apps/api',
    '<rootDir>/libs/api-interfaces',
    '<rootDir>/libs/ui',
    '<rootDir>/libs/shared-service',
    '<rootDir>/apps/client-manager',
    '<rootDir>/libs/constants',
    '<rootDir>/libs/client/features',
    '<rootDir>/libs/client-manager/features',
    '<rootDir>/libs/client-manager/guards',
    '<rootDir>/libs/client/guards',
    '<rootDir>/libs/client-manager/models',
    '<rootDir>/libs/client-manager/data-accesss',
    '<rootDir>/libs/client-manager/skill-types',
    '<rootDir>/libs/client-manager/skills',
    '<rootDir>/libs/client-manager/timelines',
    '<rootDir>/libs/client-manager/users',
    '<rootDir>/libs/client-manager/login',
  ],
};
