import { IUser } from '@workspace/api-interfaces';

export const usersData: IUser[] = [
  {
    id: 1,
    email: 'test1@test.com',
    firstName: '山田',
    lastName: '太郎',
    password: '',
    birthDay: new Date(),
    address: '',
    graduationDate: new Date(),
    qualification: '',
    sex: '',
  },
  {
    id: 2,
    email: 'test2@test.com',
    firstName: '鈴木',
    lastName: '一郎',
    password: '',
    birthDay: new Date(),
    address: '',
    graduationDate: new Date(),
    qualification: '',
    sex: '',
  },
  {
    id: 3,
    email: 'test3@test.com',
    firstName: '斉藤',
    lastName: '和義',
    password: '',
    birthDay: new Date(),
    address: '',
    graduationDate: new Date(),
    qualification: '',
    sex: '',
  },
  {
    id: 4,
    email: 'test4@test.com',
    firstName: '田中',
    lastName: '二郎',
    password: '',
    birthDay: new Date(),
    address: '',
    graduationDate: new Date(),
    qualification: '',
    sex: '',
  },
  {
    id: 5,
    email: 'test5@test.com',
    firstName: '小林',
    lastName: 'かずき',
    password: '',
    birthDay: new Date(),
    address: '',
    graduationDate: new Date(),
    qualification: '',
    sex: '',
  },
];
